//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountDetail
    {
        public long DiscountDetailId { get; set; }
        public Nullable<long> ProId { get; set; }
        public Nullable<int> DiscountProductId { get; set; }
        public Nullable<int> Amount { get; set; }
        public string TypeAmount { get; set; }
        public Nullable<int> MaxQuantityPerUser { get; set; }
        public decimal priceAfter { get; set; }


        public virtual Product Product { get; set; }
        public virtual DiscountProduct DiscountProduct { get; set; }
    }
}
