//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long FeedbackId { get; set; }
        public Nullable<long> CusID { get; set; }
        public Nullable<long> ProVariationID { get; set; }
        public Nullable<int> Stars { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Image { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ProductVariation ProductVariation { get; set; }
    }
}
