//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSection
    {
        public int ProductSectionId { get; set; }
        public Nullable<long> ProId { get; set; }
        public Nullable<int> SectionId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Section Section { get; set; }
    }
}
