//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public long ProColorID { get; set; }
        public long ProID { get; set; }
        public string Image { get; set; }
        public string DetailImage1 { get; set; }
        public string DetailImage2 { get; set; }
        public string DetailImage3 { get; set; }
        public string DetailImage4 { get; set; }
        public string DetailImage5 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductColor ProductColor { get; set; }
    }
}
