//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
            this.ProductVariations = new HashSet<ProductVariation>();
        }
    
        public long ProId { get; set; }
        public Nullable<int> CatId { get; set; }
        public string ProName { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public Nullable<System.DateTime> StartPromotion { get; set; }
        public Nullable<System.DateTime> StopPromotion { get; set; }
        public string Slug { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariation> ProductVariations { get; set; }
    }
}
