//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductImages = new HashSet<ProductImage>();
            this.DiscountDetails = new HashSet<DiscountDetail>();
            this.ProductVariations = new HashSet<ProductVariation>();
        }
    
        public long ProId { get; set; }
        public int ProCatId { get; set; }
        public string ProName { get; set; }
        public string Material { get; set; }
        public string Description { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ImportPrice { get; set; }
        public string Slug { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string firstImage { get; set; }
        public int TotalQty { get; set; }
        public decimal DiscountPrice { get; set; }
        public int Percent { get; set; }

        public virtual ProductCat ProductCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscountDetail> DiscountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductVariation> ProductVariations { get; set; }
    }
}
