//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromotionOrder()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long IDPromotionOrder { get; set; }
        public string Title { get; set; }
        public Nullable<int> PromotionPrice { get; set; }
        public Nullable<int> AmountPromotion { get; set; }
        public Nullable<System.DateTime> StartPromotion { get; set; }
        public Nullable<System.DateTime> StopPromotion { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
