//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Section()
        {
            this.ProductSections = new HashSet<ProductSection>();
        }
    
        public int SectionId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Image1 { get; set; }
        public Nullable<bool> Image2 { get; set; }
        public Nullable<bool> Image3 { get; set; }
        public string Link1 { get; set; }
        public string Link2 { get; set; }
        public string Link3 { get; set; }
        public Nullable<int> PageId { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Page Page { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSection> ProductSections { get; set; }
    }
}
