//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistical
    {
        public int statisticalId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Revenue { get; set; }
        public Nullable<int> Profit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Total_Order { get; set; }
    }
}
